import type { SceneAsset } from '@/types/app';

export const CATALOG: SceneAsset[] = [
  {
    id: 'asset-k-island',
    name: 'Arc Quartz Island',
    vendor: 'Ferguson Homes',
    category: 'Kitchen Surface',
    roomType: 'kitchen',
    color: '#e4e7ef',
    dimensions: { w: 3.0, h: 1.0, d: 1.2 },
    url: 'https://www.ferguson.com/category/kitchen-islands',
    shape: 'box',
    metallic: 0.25,
    roughness: 0.45,
  },
  {
    id: 'asset-k-stove',
    name: 'Chefline Pro Stove',
    vendor: 'Ferguson Homes',
    category: 'Kitchen Appliance',
    roomType: 'kitchen',
    color: '#1a1d24',
    dimensions: { w: 0.9, h: 0.9, d: 0.65 },
    url: 'https://www.ferguson.com/category/ranges',
    shape: 'box',
    collisionLock: 'island',
    metallic: 0.8,
    roughness: 0.25,
  },
  {
    id: 'asset-k-fridge',
    name: 'Nordic French Door Fridge',
    vendor: 'Ferguson Homes',
    category: 'Kitchen Appliance',
    roomType: 'kitchen',
    color: '#8a94a8',
    dimensions: { w: 0.92, h: 1.85, d: 0.8 },
    url: 'https://www.ferguson.com/category/refrigerators',
    shape: 'box',
    collisionLock: 'wall',
    metallic: 0.75,
    roughness: 0.2,
  },
  {
    id: 'asset-laundry-washer',
    name: 'Cleanflow Washer',
    vendor: 'Home Goods',
    category: 'Laundry Appliance',
    roomType: 'laundry',
    color: '#d8dde8',
    dimensions: { w: 0.7, h: 1.0, d: 0.72 },
    url: 'https://www.homegoods.com/laundry',
    shape: 'box',
  },
  {
    id: 'asset-office-desk',
    name: 'Atelier Office Desk',
    vendor: 'Home Goods',
    category: 'Home Office',
    roomType: 'home-office',
    color: '#4e3f33',
    dimensions: { w: 1.8, h: 0.78, d: 0.75 },
    url: 'https://www.homegoods.com/home-office',
    shape: 'box',
  },
  {
    id: 'asset-office-chair',
    name: 'Ergo Mesh Chair',
    vendor: 'Home Goods',
    category: 'Home Office',
    roomType: 'home-office',
    color: '#242936',
    dimensions: { w: 0.7, h: 1.2, d: 0.7 },
    url: 'https://www.homegoods.com/office-chairs',
    shape: 'box',
  },
  {
    id: 'asset-floral-arrangement',
    name: 'Signature Floral Arrangement',
    vendor: 'Home Goods',
    category: 'Decorative Floral',
    roomType: 'floral',
    color: '#b7798d',
    dimensions: { w: 0.45, h: 0.65, d: 0.45 },
    url: 'https://www.homegoods.com/decor/floral',
    shape: 'cylinder',
  },
];
